# Generated by Django 3.2.9 on 2022-01-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ground', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('team1', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team1', to='facup.team')),
                ('team10', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team10', to='facup.team')),
                ('team11', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team11', to='facup.team')),
                ('team12', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team12', to='facup.team')),
                ('team13', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team13', to='facup.team')),
                ('team14', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team14', to='facup.team')),
                ('team2', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team2', to='facup.team')),
                ('team3', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team3', to='facup.team')),
                ('team4', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team4', to='facup.team')),
                ('team5', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team5', to='facup.team')),
                ('team6', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team6', to='facup.team')),
                ('team7', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team7', to='facup.team')),
                ('team8', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team8', to='facup.team')),
                ('team9', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team9', to='facup.team')),
            ],
        ),
    ]
