# Generated by Django 3.2.9 on 2022-01-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team10', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team11', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team12', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team13', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team14', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team3', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team4', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team5', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team6', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team7', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team8', to='facup.team'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='team9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team9', to='facup.team'),
        ),
    ]
