# Generated by Django 3.2.9 on 2022-01-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='teams',
        ),
        migrations.AddField(
            model_name='stat',
            name='teams',
            field=models.ManyToManyField(to='facup.Team'),
        ),
    ]
