# Generated by Django 3.2.9 on 2022-01-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0002_auto_20220104_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
