# Generated by Django 3.2.9 on 2021-12-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0002_auto_20211229_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='team',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
