# Generated by Django 3.2.9 on 2022-01-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='username',
        ),
        migrations.AddField(
            model_name='stat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='facup.user'),
        ),
    ]
