# Generated by Django 3.2.9 on 2022-01-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0004_auto_20220112_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='ROLE_USER', max_length=100),
        ),
    ]
