# Generated by Django 3.2.9 on 2022-01-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='year',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
