# Generated by Django 3.2.9 on 2022-01-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0006_stat_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
