# Generated by Django 3.2.9 on 2022-03-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0007_alter_stat_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='user',
            new_name='username',
        ),
    ]
