# Generated by Django 4.0 on 2022-04-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0008_rename_user_stat_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
