# Generated by Django 4.0 on 2022-04-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0009_alter_stat_team1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='facup.team'),
        ),
    ]
