# Generated by Django 4.0 on 2022-04-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facup', '0011_alter_stat_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
